ugh… git commands are an inconsistency hell in itself
git reflog expire --expire=a̲l̲l̲ is documented, even though the code
only uses parse_expiry_date() which handles all and now the same,
so --expire=now would also work (and is in fact recommended by git
help filter-branch but undocumented in git help reflog!); git gc
--prune=n̲o̲w̲ is handled specially, one use is parse_expiry_date()
(which also accepts --prune=all, which I’ve seen recommended lots
over the years), the other is a direct strcmp with "now" (matching
*its* documentation but not lots of info elsewhere)… so we now use
--expire=all --all and --prune=now despite wanting the identical
thing…

diff --git a/cvs2git b/cvs2git
--- a/cvs2git
+++ b/cvs2git
@@ -226,7 +226,7 @@ if (( do_grafts )); then
 fi
 
 $git reflog expire --expire=all --all || die "git reflog failed with errorlevel $?"
-$git gc --aggressive --prune=all || die "git gc failed with errorlevel $?"
+$git gc --aggressive --prune=now || die "git gc failed with errorlevel $?"
 print -u2 "I: $SECONDS seconds elapsed for garbage collection"
 for rem in "${remote[@]}"; do
 	print -ru2 "D: pushing to $rem"
